ALTER TABLE "admin_invitations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "admin_users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "project_amenities" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "project_categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "project_checklist_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "project_facts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "project_media" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "project_tags" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "project_units" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "projects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "media_assets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "form_fields" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "forms" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "leads" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "brochures" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "insights" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ai_visibility_prompts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "ai_visibility_results" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "gsc_performance_cache" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "seo_configs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "seo_global_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "seo_issues" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tracking_event_destinations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tracking_events" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "tracking_integrations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "site_settings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "insight_categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "company_content" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "home_content" ENABLE ROW LEVEL SECURITY;